/* eslint-disable @typescript-eslint/naming-convention */
// Generated by https://quicktype.io

export interface IAppJSON {
    id:                      string;
    name:                    string;
    publisher:               string;
    version:                 string;
    brief:                   string;
    description:             string;
    privacyStatement:        string;
    EULA:                    string;
    help:                    string;
    url:                     string;
    logo:                    string;
    dependencies:            IAppJsonDependency[];
    screenshots:             any[];
    platform:                string;
    idRanges:                IAppJsonIdRange[];
    contextSensitiveHelpUrl: string;
    showMyCode:              boolean;
    runtime:                 string;
    target:                  string;
    supportedLocales:        string[];
    features:                string[];
    suppressWarnings:        string[];
    applicationInsightsKey:  string;
}

export interface IAppJsonDependency {
    id:        string;
    publisher: string;
    name:      string;
    version:   string;
}

export interface IAppJsonIdRange {
    from: number;
    to:   number;
}
